<?php
$dictionary["Lead"]["fields"]["sugarfield_status"] = array (
  'required' => false,
  'name' => 'sugarfield_status',
  'vname' => 'LBL_SUGARFIELD_status',
   'type' => 'enum',
  'massupdate' => 0,
  'no_default' => false,
  'options'=>'status_dropdown',
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'disabled',
  'duplicate_merge_dom_value' => '0',
  'audited' => false,
  'reportable' => true,
  'unified_search' => true,
  'merge_filter' => 'disabled',
  'len' => '255',
  'size' => '20',
);
