var SubAgentsDummyData = [
    {
        "Name": "IGEC-Sub agent demo",
        "ID": "778f0726-ab59-513a-ddbb-5ccaec296934",
        "Website": "http://igecglobal.com",
        "Email Address": "igec1@igec.com.au",
        "Non Primary E-mails": "",
        "Office Phone": "",
        "Alternate Phone": "",
        "Fax": "",
        "Billing Street": "",
        "Billing City": "",
        "Billing State": "",
        "Billing Postal Code": "",
        "Billing Country": "",
        "Shipping Street": "",
        "Shipping City": "",
        "Shipping State": "",
        "Shipping Postal Code": "",
        "Shipping Country": "",
        "Description": "",
        "Industry": "",
        "Annual Revenue": "",
        "Employees": "",
        "Ticker Symbol": "",
        "Ownership": "",
        "Rating": "",
        "Assigned to": "",
        "Assigned User Id": "",
        "Date Created": "05/02/2019 04:12 pm",
        "Date Modified": "05/02/2019 04:12 pm",
        "Modified By": 1,
        "Created By": 1,
        "Deleted": 0,
        "Type": "",
        "Default User ID": "2c4d569d-9953-0302-3ea8-5c76549a750c"
    },
    {
        "Name": "4S Study Abroad Consultants",
        "ID": "edf1ae1d-0422-10a8-5aae-5cda589da07f",
        "Website": "http://www.4sstudyabroad.com/",
        "Email Address": "",
        "Non Primary E-mails": "joanna@4sstudyabroad.com;shaima@4sstudyabroad.com;shipra@4sstudyabroad.com",
        "Office Phone": "0097 14 5538909",
        "Alternate Phone": "",
        "Fax": "0097 14 5547849",
        "Billing Street": "Office F 39, Block 2A",
        "Billing City": "Dubai Knowledge Village",
        "Billing State": "Dubai",
        "Billing Postal Code": "",
        "Billing Country": "United Arab Emirates",
        "Shipping Street": "Office F 39, Block 2A",
        "Shipping City": "Dubai Knowledge Village",
        "Shipping State": "Dubai",
        "Shipping Postal Code": "",
        "Shipping Country": "United Arab Emirates",
        "Description": "",
        "Industry": "",
        "Annual Revenue": "",
        "Employees": "",
        "Ticker Symbol": "",
        "Ownership": "",
        "Rating": "",
        "Assigned to": "",
        "Assigned User Id": "",
        "Date Created": "05/14/2019 08:57 am",
        "Date Modified": "05/14/2019 08:57 am",
        "Modified By": "6ff813b6-2dc4-8251-5270-5c7e2207b66d",
        "Created By": "6ff813b6-2dc4-8251-5270-5c7e2207b66d",
        "Deleted": 0,
        "Type": "Competitor",
        "Default User ID": "6ff813b6-2dc4-8251-5270-5c7e2207b66d"
    },
    {
        "Name": "Education Zone",
        "ID": "ef8d0746-8ce1-d1ed-9325-5cda594919bb",
        "Website": "https://www.ezone.ae/",
        "Email Address": "newstudent@ezone.ae",
        "Non Primary E-mails": "",
        "Office Phone": "+971 4 3910257",
        "Alternate Phone": "",
        "Fax": "+971 4 3664512",
        "Billing Street": "Block 2B | Office F30",
        "Billing City": "Dubai Knowledge Village",
        "Billing State": "Dubai",
        "Billing Postal Code": 214592,
        "Billing Country": "United Arab Emirates",
        "Shipping Street": "",
        "Shipping City": "",
        "Shipping State": "",
        "Shipping Postal Code": "",
        "Shipping Country": "",
        "Description": "",
        "Industry": "",
        "Annual Revenue": "",
        "Employees": "",
        "Ticker Symbol": "",
        "Ownership": "",
        "Rating": "",
        "Assigned to": "",
        "Assigned User Id": "",
        "Date Created": "05/14/2019 09:01 am",
        "Date Modified": "05/14/2019 09:01 am",
        "Modified By": "6ff813b6-2dc4-8251-5270-5c7e2207b66d",
        "Created By": "6ff813b6-2dc4-8251-5270-5c7e2207b66d",
        "Deleted": 0,
        "Type": "Competitor",
        "Default User ID": "6ff813b6-2dc4-8251-5270-5c7e2207b66d"
    },
    {
        "Name": "DM Consultants",
        "ID": "8bdca83b-a776-28ae-2251-5cda5c62e569",
        "Website": "http://www.dm-consultant.com/",
        "Email Address": "heena@dm-consultant.com",
        "Non Primary E-mails": "",
        "Office Phone": "+971 (0)4 329 6687",
        "Alternate Phone": "",
        "Fax": "+971 (0)4 886 8870",
        "Billing Street": "Office 3402, Latifa Tower  East Wing",
        "Billing City": "Sheikh Zayed Road Next to Crown Plaza",
        "Billing State": "Dubai",
        "Billing Postal Code": 29514,
        "Billing Country": "United Arab Emirates",
        "Shipping Street": "Office 3402, Latifa Tower  East Wing",
        "Shipping City": "Sheikh Zayed Road Next to Crown Plaza",
        "Shipping State": "Dubai",
        "Shipping Postal Code": 29514,
        "Shipping Country": "United Arab Emirates",
        "Description": "",
        "Industry": "",
        "Annual Revenue": "",
        "Employees": "",
        "Ticker Symbol": "",
        "Ownership": "",
        "Rating": "",
        "Assigned to": "",
        "Assigned User Id": "",
        "Date Created": "05/14/2019 09:12 am",
        "Date Modified": "05/14/2019 09:12 am",
        "Modified By": "6ff813b6-2dc4-8251-5270-5c7e2207b66d",
        "Created By": "6ff813b6-2dc4-8251-5270-5c7e2207b66d",
        "Deleted": 0,
        "Type": "Competitor",
        "Default User ID": "6ff813b6-2dc4-8251-5270-5c7e2207b66d"
    },
    {
        "Name": "UNIPASS",
        "ID": "9f961e57-6374-dc41-7255-5ce67b0d08db",
        "Website": "http://unipass.co.ke/",
        "Email Address": "applications@unipass.co.ke",
        "Non Primary E-mails": "",
        "Office Phone": "+254 726 907236",
        "Alternate Phone": "",
        "Fax": "",
        "Billing Street": "PO Box 787 - 00606",
        "Billing City": "Kush Office Suite No 5 91 Rhapta Road",
        "Billing State": "Corner of Rhapta and Church Road",
        "Billing Postal Code": "Westlands Nairobi 00",
        "Billing Country": "Kenya",
        "Shipping Street": "",
        "Shipping City": "",
        "Shipping State": "",
        "Shipping Postal Code": "",
        "Shipping Country": "",
        "Description": "",
        "Industry": "",
        "Annual Revenue": "",
        "Employees": "",
        "Ticker Symbol": "",
        "Ownership": "",
        "Rating": "",
        "Assigned to": "",
        "Assigned User Id": "",
        "Date Created": "05/23/2019 01:51 pm",
        "Date Modified": "05/23/2019 01:51 pm",
        "Modified By": "6ff813b6-2dc4-8251-5270-5c7e2207b66d",
        "Created By": "6ff813b6-2dc4-8251-5270-5c7e2207b66d",
        "Deleted": 0,
        "Type": "Reseller",
        "Default User ID": "6ff813b6-2dc4-8251-5270-5c7e2207b66d"
    },
    {
        "Name": "IGEC Irbid  Branch",
        "ID": "8e732d59-772c-7e59-5063-5cff5b40aaec",
        "Website": "http://",
        "Email Address": "m.talafha@igec.com.au",
        "Non Primary E-mails": "",
        "Office Phone": "962 7247415",
        "Alternate Phone": "",
        "Fax": "",
        "Billing Street": "University Street , Opposite Archaeology Gate",
        "Billing City": "Mahdi Tawfsheh Building  Office #207",
        "Billing State": "Irbid",
        "Billing Postal Code": "",
        "Billing Country": "Jordan",
        "Shipping Street": "",
        "Shipping City": "",
        "Shipping State": "",
        "Shipping Postal Code": "",
        "Shipping Country": "",
        "Description": "",
        "Industry": "",
        "Annual Revenue": "",
        "Employees": "",
        "Ticker Symbol": "",
        "Ownership": "",
        "Rating": "",
        "Assigned to": "",
        "Assigned User Id": "",
        "Date Created": "06/11/2019 10:42 am",
        "Date Modified": "06/11/2019 10:42 am",
        "Modified By": "6ff813b6-2dc4-8251-5270-5c7e2207b66d",
        "Created By": "6ff813b6-2dc4-8251-5270-5c7e2207b66d",
        "Deleted": 0,
        "Type": "Reseller",
        "Default User ID": "d78b7ec5-6931-1543-9f1e-5c7e25166998"
    },
    {
        "Name": "Education Resources Network",
        "ID": "6ae66a8b-6ac0-5f8f-4034-5d00f17f49e6",
        "Website": "http://ern-dubai.com/",
        "Email Address": "basima@ern-dubai.com",
        "Non Primary E-mails": "",
        "Office Phone": "+971 43685697",
        "Alternate Phone": "",
        "Fax": "+971 44393587",
        "Billing Street": "REN Management Consultancy",
        "Billing City": "Prime Tower Alabraj St. Business Bay",
        "Billing State": "Dubai",
        "Billing Postal Code": "",
        "Billing Country": "United Arab Emirates",
        "Shipping Street": "",
        "Shipping City": "",
        "Shipping State": "",
        "Shipping Postal Code": "",
        "Shipping Country": "",
        "Description": "",
        "Industry": "",
        "Annual Revenue": "",
        "Employees": "",
        "Ticker Symbol": "",
        "Ownership": "",
        "Rating": "",
        "Assigned to": "",
        "Assigned User Id": "",
        "Date Created": "06/12/2019 03:33 pm",
        "Date Modified": "06/12/2019 03:33 pm",
        "Modified By": "6ff813b6-2dc4-8251-5270-5c7e2207b66d",
        "Created By": "6ff813b6-2dc4-8251-5270-5c7e2207b66d",
        "Deleted": 0,
        "Type": "Competitor",
        "Default User ID": "6ff813b6-2dc4-8251-5270-5c7e2207b66d"
    }
]